apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  type: NodePort # Use LoadBalancer in real cloud
  ports:
    - port: 8090
      targetPort: 8080
      nodePort: 30090 # Exposed on localhost:30090
